# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
  
name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      manifest_json_url:
        description: 'Something like https://my-twa.com/manifest.json'
        required: true
        type: string
        
permissions:
    contents: write
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    # - uses: actions/setup-java@v5
    #   with:
    #     distribution: 'temurin' # See 'Supported distributions' for available options
    #     java-version: '17'
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm i -g @bubblewrap/cli
    
    - run: |
        bubblewrap init --manifest ${{ github.event.inputs.manifest_json_url }} -y && \
        bubblewrap build && \
        ls -R
        
    # - name: Archive Release
    #   uses: thedoctor0/zip-release@master
    #   with:
    #     type: 'zip'
    #     path: ${{ github.event.repository.name }}*
    #     filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
        
    # - name: Release prebuilt
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
    #     allowUpdates: true
    #     token: ${{ secrets.GITHUB_TOKEN }}
