# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
  
name: Node.js CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' 
      
permissions:
    contents: write
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - id: jdk
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm i -g @bubblewrap/cli
    
    - run: |
        cat << EOF > ~/.bubblewrap/config.json
        {"jdkPath": "${{ steps.jdk.outputs.path }}", "androidSdkPath": "~/.android/sdk"}
        EOF

    # bubblewrap should not keep recommending when i proactively set the config
    # bubblewrap updateConfig --androidSdkPath "~/.android/sdk" --jdkPath "${{ steps.jdk.outputs.path }}"
        
    - name: Build TWA
      run: |
        echo "${{ secrets.KEYSTORE_BASE64_ENCODED }}" > android.keystore && \
        echo y | bubblewrap build --skipPwaValidation
      env:
        BUBBLEWRAP_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        BUBBLEWRAP_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    
    - run: |
        ls -R
        
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: |
          "app-release-bundle.aab"
          "app-release-signed.apk"
        filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-node-v${{ matrix.node-version }}.zip"
        
    - name: Release prebuilt
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.event.repository.name }}-${{ github.ref_name }}-node-v${{ matrix.node-version }}.zip"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
